In [2]:
import pandas as pd

In [3]:
rel2015 = pd.read_csv('2015.csv')
rel2016 = pd.read_csv('2016.csv')

In [4]:
rel2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204

In [5]:
rel2016.head(3)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137

Celulas diferentes:
2015 Standard Erro <=> 2016 Lower Confidence Interval / Upper Confidence Interval

In [6]:
rel2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [7]:
rel2015.shape

(158, 12)

In [8]:
rel2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [9]:
rel2016.shape

(157, 13)

Juntar as duas tabelas

In [10]:
df = pd.concat([rel2015, rel2016], ignore_index=True, join='inner')

In [14]:
df.head(30)

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
5,Finland,Western Europe,6,7.406,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351,2.61955
6,Netherlands,Western Europe,7,7.378,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610,2.46570
7,Sweden,Western Europe,8,7.364,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262,2.37119
8,New Zealand,Australia and New Zealand,9,7.286,1.25018,1.31967,0.90837,0.63938,0.42922,0.47501,2.26425
9,Australia,Australia and New Zealand,10,7.284,1.33358,1.30923,0.93156,0.65124,0.35637,0.43562,2.26646
10,Israel,Middle East and Northern Africa,11,7.278,1.22857,1.22393,0.91387,0.41319,0.07785,0.33172,3.08854
11,Costa Rica,Latin America and Caribbean,12,7.226,0.95578,1.23788,0.86027,0.63376,0.10583,0.25497,3.17728
12,Austria,Western Europe,13,7.200,1.33723,1.29704,0.89042,0.62433,0.18676,0.33088,2.53320
13,Mexico,Latin America and Caribbean,14,7.187,1.02054,0.91451,0.81444,0.48181,0.21312,0.14074,3.60214
14,United States,North America,15,7.119,1.39451,1.24711,0.86179,0.54604,0.15890,0.40105,2.51011
15,Brazil,Latin America and Caribbean,16,6.983,0.98124,1.23287,0.69702,0.49049,0.17521,0.14574,3.26001
16,Luxembourg,Western Europe,17,6.946,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
17,Ireland,Western Europe,18,6.940,1.33596,1.36948,0.89533,0.61777,0.28703,0.45901,1.97570
18,Belgium,Western Europe,19,6.937,1.30782,1.28566,0.89667,0.58450,0.22540,0.22250,2.41484
19,United Arab Emirates,Middle East and Northern Africa,20,6.901,1.42727,1.12575,0.80925,0.64157,0.38583,0.26428,2.24743
20,United Kingdom,Western Europe,21,6.867,1.26637,1.28548,0.90943,0.59625,0.32067,0.51912,1.96994
21,Oman,Middle East and Northern Africa,22,6.853,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489
22,Venezuela,Latin America and Caribbean,23,6.810,1.04424,1.25596,0.72052,0.42908,0.11069,0.05841,3.19131
23,Singapore,Southeastern Asia,24,6.798,1.52186,1.02000,1.02525,0.54252,0.49210,0.31105,1.88501
24,Panama,Latin America and Caribbean,25,6.786,1.06353,1.19850,0.79661,0.54210,0.09270,0.24434,2.84848
25,Germany,Western Europe,26,6.750,1.32792,1.29937,0.89186,0.61477,0.21843,0.28214,2.11569
26,Chile,Latin America and Caribbean,27,6.670,1.10715,1.12447,0.85857,0.44132,0.12869,0.33363,2.67585
27,Qatar,Middle East and Northern Africa,28,6.611,1.69042,1.07860,0.79733,0.64040,0.52208,0.32573,1.55674
28,France,Western Europe,29,6.575,1.27778,1.26038,0.94579,0.55011,0.20646,0.12332,2.21126
29,Argentina,Latin America and Caribbean,30,6.574,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600

In [12]:
df.shape

(315, 11)

Encontrar os numeros Nulos: não encontrei

In [45]:
def show_nulls2016(rel2016):
    total_nan2016 = rel2016.isnull().sum()
    perc_nan2016 = total_nan2016/len(rel2016)*100
    return total_nan2016, perc_nan2016

In [46]:
print('total_nulos 2016', show_nulls2016(rel2016=rel2016)[0])

total_nulos 2016 Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Lower Confidence Interval        0
Upper Confidence Interval        0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [47]:
def show_nulls2015(rel2015):
    total_nan2015 = rel2015.isnull().sum()
    perc_nan2015 = total_nan2015/len(rel2015)*100
    return total_nan2015, perc_nan2015

In [48]:
print('Total nulos 2015', show_nulls2015(rel2015=rel2015)[0])

Total nulos 2015 Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [49]:
def show_nulls(df):
    total_nan = df.isnull().sum()
    perc_nan = total_nan/len(df)*100
    return total_nan, perc_nan

In [50]:
print('total_nulos', show_nulls(df=df)[0])

total_nulos Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [55]:
from plotnine import *

ModuleNotFoundError: No module named 'plotnine'

In [1]:
(
        ggplot(df) + 
            geom_histogram(aes(x='Happiness Score'), color = 'read')
)

NameError: name 'ggplot' is not defined